services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: community-backend-dev
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env.production.local
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: community-nginx-dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
