const MIN_CONTENT_LENGTH = 5;
const MAX_CONTENT_LENGTH = 1_000_000;

export const CONTENT_LEN = {
  MIN: MIN_CONTENT_LENGTH,
  MAX: MAX_CONTENT_LENGTH,
};

const MIN_COMMENT_LENGTH = 5;
const MAX_COMMENT_LENGTH = 10000;
export const COMMENT_LEN = {
  MIN: MIN_COMMENT_LENGTH,
  MAX: MAX_COMMENT_LENGTH,
};
